[package]
name = "envy"
version = "0.2.0"
edition = "2021"
description = "envy — universal, blazing-fast environment configuration manager for every stack"
license = "MIT"
repository = "https://github.com/MaNiSh-9211/envy"
readme = "README.md"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
colored = "2"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
aes-gcm = "0.10"
base64 = "0.22"
keyring = { version = "3", features = ["windows-native", "apple-native", "sync-secret-service"] }
rand = "0.8"
sha2 = "0.10"

[profile.release]
lto = true
strip = true
codegen-units = 1
