//! Multi-format translation: turn resolved configuration into the native
//! format any framework expects — `.env`, `.env.docker`, Spring Boot
//! `application.properties`, JSON, YAML.

use std::collections::BTreeMap;

pub const FORMAT_ENV: &str = "env";
pub const FORMAT_DOCKER: &str = "docker";
pub const FORMAT_PROPERTIES: &str = "properties";
pub const FORMAT_JSON: &str = "json";
pub const FORMAT_YAML: &str = "yaml";

pub const FORMATS: &[&str] = &[FORMAT_ENV, FORMAT_DOCKER, FORMAT_PROPERTIES, FORMAT_JSON, FORMAT_YAML];

pub fn default_filename(format: &str) -> &'static str {
    match format {
        FORMAT_DOCKER => ".env.docker",
        FORMAT_PROPERTIES => "application.properties",
        FORMAT_JSON => "envy.config.json",
        FORMAT_YAML => "envy.export.yaml",
        _ => ".env",
    }
}

fn quote_env_value(value: &str) -> String {
    if value.contains(char::is_whitespace) || value.contains('"') || value.contains('\'') {
        format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
    } else {
        value.to_string()
    }
}

/// SCREAMING_SNAKE_CASE → spring.style.dotted.lowercase
pub fn properties_key(key: &str) -> String {
    key.split('_')
        .filter(|part| !part.is_empty())
        .map(|part| part.to_ascii_lowercase())
        .collect::<Vec<_>>()
        .join(".")
}

pub fn render(format: &str, values: &BTreeMap<String, String>) -> String {
    match format {
        FORMAT_PROPERTIES => render_properties(values),
        FORMAT_JSON => render_json(values),
        FORMAT_YAML => render_yaml(values),
        _ => render_env(values),
    }
}

fn render_env(values: &BTreeMap<String, String>) -> String {
    let mut out = String::from("# generated by envy — do not commit secrets\n");
    for (key, value) in values {
        out.push_str(&format!("{key}={}\n", quote_env_value(value)));
    }
    out
}

fn render_properties(values: &BTreeMap<String, String>) -> String {
    let mut out = String::from("# generated by envy — Spring Boot style properties\n");
    for (key, value) in values {
        out.push_str(&format!("{}={}\n", properties_key(key), escape_properties_value(value)));
    }
    out
}

fn escape_properties_value(value: &str) -> String {
    value.replace('\\', "\\\\").replace('\n', "\\n")
}

fn render_json(values: &BTreeMap<String, String>) -> String {
    let ordered: BTreeMap<&str, &str> =
        values.iter().map(|(k, v)| (k.as_str(), v.as_str())).collect();
    serde_json::to_string_pretty(&ordered).expect("json serialises") + "\n"
}

fn render_yaml(values: &BTreeMap<String, String>) -> String {
    let mut out = String::from("# generated by envy\n");
    let yaml = serde_yaml::to_string(values).expect("yaml serialises");
    out.push_str(yaml.trim_start_matches("---\n").trim_end());
    out.push('\n');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> BTreeMap<String, String> {
        BTreeMap::from([
            ("DATABASE_URL".to_string(), "postgresql://u:p@db/xyz".to_string()),
            ("GREETING".to_string(), "hello world".to_string()),
            ("PORT".to_string(), "8080".to_string()),
        ])
    }

    #[test]
    fn env_quotes_spaces_and_keeps_plain() {
        let rendered = render(FORMAT_ENV, &sample());
        assert!(rendered.contains("DATABASE_URL=postgresql://u:p@db/xyz\n"));
        assert!(rendered.contains("GREETING=\"hello world\"\n"));
        assert!(rendered.contains("PORT=8080\n"));
    }

    #[test]
    fn properties_lowercases_with_dots() {
        let rendered = render(FORMAT_PROPERTIES, &sample());
        assert!(rendered.contains("database.url=postgresql://u:p@db/xyz\n"));
        assert!(rendered.contains("port=8080\n"));
        assert!(!rendered.contains("DATABASE_URL="));
    }

    #[test]
    fn json_is_pretty_and_complete() {
        let rendered = render(FORMAT_JSON, &sample());
        let parsed: serde_json::Value = serde_json::from_str(&rendered).expect("valid json");
        assert_eq!(parsed["PORT"], "8080");
        assert_eq!(parsed["GREETING"], "hello world");
    }

    #[test]
    fn yaml_renders_mapping() {
        let rendered = render(FORMAT_YAML, &sample());
        assert!(rendered.contains("PORT: '8080'") || rendered.contains("PORT: \"8080\"") || rendered.contains("PORT: 8080"));
        assert!(rendered.contains("DATABASE_URL:"));
    }

    #[test]
    fn docker_uses_env_renderer() {
        assert_eq!(render(FORMAT_DOCKER, &sample()), render(FORMAT_ENV, &sample()));
        assert_eq!(default_filename(FORMAT_DOCKER), ".env.docker");
        assert_eq!(default_filename(FORMAT_PROPERTIES), "application.properties");
    }

    #[test]
    fn properties_key_conversion() {
        assert_eq!(properties_key("DATABASE_URL"), "database.url");
        assert_eq!(properties_key("PORT"), "port");
        assert_eq!(properties_key("SPRING__DOUBLE"), "spring.double");
    }
}
