use crate::schema::{EnvySchema, VarSpec};

pub enum Target {
    TypeScript,
    Go,
    Java,
    Python,
}

impl Target {
    pub fn default_filename(&self) -> &'static str {
        match self {
            Target::TypeScript => "envy.d.ts",
            Target::Go => "envy_config.go",
            Target::Java => "EnvyConfig.java",
            Target::Python => "envy_config.py",
        }
    }

#[allow(dead_code)]
pub fn parse(s: &str) -> Option<Target> {
        match s {
            "typescript" | "ts" => Some(Target::TypeScript),
            "go" | "golang" => Some(Target::Go),
            "java" | "spring" => Some(Target::Java),
            "python" | "py" => Some(Target::Python),
            _ => None,
        }
    }
}

pub fn generate(target: &Target, schema: &EnvySchema, package: &str) -> String {
    match target {
        Target::TypeScript => typescript(schema),
        Target::Go => go(schema, package),
        Target::Java => java(schema, package),
        Target::Python => python(schema),
    }
}

// ---------- casing ----------

fn parts(key: &str) -> Vec<String> {
    key.split('_')
        .filter(|p| !p.is_empty())
        .map(|p| p.to_ascii_lowercase())
        .collect()
}

fn pascal(key: &str) -> String {
    parts(key)
        .iter()
        .map(|p| {
            let mut chars = p.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

#[cfg(test)]
fn snake(key: &str) -> String {
    parts(key).join("_")
}

fn is_required(spec: &VarSpec) -> bool {
    spec.required && spec.default.is_none()
}

fn escape_double_quoted(raw: &str) -> String {
    raw.replace('\\', "\\\\").replace('"', "\\\"")
}

fn yaml_default_string(spec: &VarSpec) -> Option<String> {
    spec.default.as_ref().and_then(|d| crate::resolver::scalar_to_string(d).ok())
}

// ---------- TypeScript ----------

fn typescript(schema: &EnvySchema) -> String {
    let mut out = String::from("// Generated by envy — DO NOT EDIT.\n\n");
    out.push_str("declare global {\n  namespace NodeJS {\n    interface ProcessEnv {\n");
    for (key, spec) in &schema.config {
        let optional = if is_required(spec) { "" } else { "?" };
        out.push_str(&format!("      {key}{optional}: string;\n"));
    }
    out.push_str("    }\n  }\n}\n\nexport {};\n");
    out
}

// ---------- Go ----------

fn go_type(spec: &VarSpec) -> &'static str {
    match spec.r#type.as_str() {
        "integer" => "int64",
        "number" | "float" => "float64",
        "boolean" | "bool" => "bool",
        _ => "string",
    }
}

fn go(schema: &EnvySchema, package: &str) -> String {
    let mut out = String::from("// Code generated by envy — DO NOT EDIT.\n\n");
    out.push_str(&format!("package {package}\n\nimport (\n\t\"errors\"\n\t\"os\"\n\t\"strconv\"\n)\n\ntype Config struct {{\n"));
    for (key, spec) in &schema.config {
        out.push_str(&format!("\t{} {} `env:\"{key}\"`\n", pascal(key), go_type(spec)));
    }
    out.push_str("}\n\nfunc Load() (*Config, error) {\n\tcfg := &Config{}\n");

    for (key, spec) in &schema.config {
        let field = pascal(key);
        let ty = go_type(spec);
        match ty {
            "string" => {
                if is_required(spec) {
                    out.push_str(&format!(
                        "\tif v, ok := os.LookupEnv(\"{key}\"); ok && v != \"\" {{\n\t\tcfg.{field} = v\n\t}} else {{\n\t\treturn nil, errors.New(\"missing required env var {key}\")\n\t}}\n"
                    ));
                } else {
                    let default = yaml_default_string(spec).unwrap_or_default();
                    out.push_str(&format!(
                        "\tcfg.{field} = os.Getenv(\"{key}\")\n\tif cfg.{field} == \"\" {{\n\t\tcfg.{field} = \"{default}\"\n\t}}\n"
                    ));
                }
            }
            _ => {
                let default = yaml_default_string(spec).unwrap_or_else(|| default_for(ty));
                let parse_stmt = match ty {
                    "int64" => {
                        "parsed, err := strconv.ParseInt(v, 10, 64)\n\t\tif err != nil {\n\t\t\treturn nil, errors.New(\"env KEY: invalid integer: \" + v)\n\t\t}"
                    }
                    "float64" => {
                        "parsed, err := strconv.ParseFloat(v, 64)\n\t\tif err != nil {\n\t\t\treturn nil, errors.New(\"env KEY: invalid number: \" + v)\n\t\t}"
                    }
                    _ => {
                        "parsed, err := strconv.ParseBool(v)\n\t\tif err != nil {\n\t\t\treturn nil, errors.New(\"env KEY: invalid boolean: \" + v)\n\t\t}"
                    }
                }
                .replace("KEY", key);
                out.push_str(&format!(
                    "\tif v, ok := os.LookupEnv(\"{key}\"); ok && v != \"\" {{\n\t\t{parse_stmt}\n\t\tcfg.{field} = parsed\n\t}} else {{\n\t\tcfg.{field} = {default}\n\t}}\n"
                ));
            }
        }
    }

    out.push_str("\treturn cfg, nil\n}\n");
    out
}

fn default_for(ty: &str) -> String {
    match ty {
        "bool" => "false".to_string(),
        "int64" => "0".to_string(),
        "float64" => "0".to_string(),
        _ => "\"\"".to_string(),
    }
}

// ---------- Java (Spring) ----------

fn java_type(spec: &VarSpec) -> &'static str {
    match spec.r#type.as_str() {
        "integer" => "long",
        "number" | "float" => "double",
        "boolean" | "bool" => "boolean",
        _ => "String",
    }
}

fn java_default(spec: &VarSpec, ty: &str) -> String {
    match yaml_default_string(spec) {
        Some(raw) => match ty {
            "String" => format!("\"{}\"", escape_double_quoted(&raw)),
            _other => raw,
        },
        None => match ty {
            "String" => "null".to_string(),
            "boolean" => "false".to_string(),
            _other => "0".to_string(),
        },
    }
}

fn java(schema: &EnvySchema, package: &str) -> String {
    let mut params = String::new();
    let mut assignments = String::new();
    let mut fields = String::new();
    let mut getters = String::new();

    for (key, spec) in &schema.config {
        let field = camel(key);
        let ty = java_type(spec);
        let placeholder = if is_required(spec) {
            format!("${{{key}}}")
        } else {
            format!("${{{key}:{}}}", java_default(spec, ty))
        };
        fields.push_str(&format!("    private final {ty} {field};\n"));
        params.push_str(&format!(
            "            @Value(\"{placeholder}\") {ty} {field},\n"
        ));
        assignments.push_str(&format!("        this.{field} = {field};\n"));
        getters.push_str(&format!(
            "    public {ty} get{}() {{\n        return {field};\n    }}\n\n",
            pascal(key)
        ));
    }

    let params = params.trim_end_matches(",\n").to_string();

    let mut out = String::from("// Generated by envy — DO NOT EDIT.\n\n");
    out.push_str(&format!("package {package};\n\n"));
    out.push_str("import org.springframework.beans.factory.annotation.Value;\n");
    out.push_str("import org.springframework.stereotype.Component;\n\n");
    out.push_str("@Component\npublic class EnvyConfig {\n\n");
    out.push_str(&fields);
    out.push('\n');
    out.push_str("    public EnvyConfig(\n");
    out.push_str(&params);
    out.push_str("\n    ) {\n");
    out.push_str(&assignments);
    out.push_str("    }\n\n");
    out.push_str(&getters);
    out.push_str("}\n");
    out
}

fn camel(key: &str) -> String {
    let pascal_name = pascal(key);
    let mut chars = pascal_name.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

// ---------- Python ----------

fn python(schema: &EnvySchema) -> String {
    let mut out = String::from("\"\"\"Generated by envy — DO NOT EDIT.\"\"\"\n\nimport os\n\n\ndef _require(key):\n    value = os.environ.get(key)\n    if not value:\n        raise RuntimeError(f\"missing required env var {key} (hint: envy run <cmd>)\")\n    return value\n\n\ndef _bool(value):\n    return value.strip().lower() in {\"1\", \"true\", \"yes\", \"on\"}\n\n");

    for (key, spec) in &schema.config {
        let line = match spec.r#type.as_str() {
            "integer" => {
                if is_required(spec) {
                    format!("{key} = int(_require(\"{key}\"))")
                } else {
                    let default = yaml_default_string(spec).unwrap_or_else(|| "0".into());
                    format!("{key} = int(os.environ.get(\"{key}\", \"{default}\"))")
                }
            }
            "number" | "float" => {
                if is_required(spec) {
                    format!("{key} = float(_require(\"{key}\"))")
                } else {
                    let default = yaml_default_string(spec).unwrap_or_else(|| "0.0".into());
                    format!("{key} = float(os.environ.get(\"{key}\", \"{default}\"))")
                }
            }
            "boolean" | "bool" => {
                if is_required(spec) {
                    format!("{key} = _bool(_require(\"{key}\"))")
                } else {
                    let default = yaml_default_string(spec).unwrap_or_else(|| "false".into());
                    format!("{key} = _bool(os.environ.get(\"{key}\", \"{default}\"))")
                }
            }
            _ => {
                if is_required(spec) {
                    format!("{key} = _require(\"{key}\")")
                } else {
                    let default = yaml_default_string(spec).unwrap_or_default();
                    format!("{key} = os.environ.get(\"{key}\", \"{default}\")")
                }
            }
        };
        out.push_str(&line);
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    fn schema(yaml: &str) -> EnvySchema {
        serde_yaml::from_str(yaml).expect("schema")
    }

    #[test]
    fn casing_helpers() {
        assert_eq!(pascal("DATABASE_URL"), "DatabaseUrl");
        assert_eq!(camel("DATABASE_URL"), "databaseUrl");
        assert_eq!(snake("DATABASE_URL"), "database_url");
    }

    #[test]
    fn typescript_marks_required_props() {
        let s = schema(
            "version: \"1\"\nservice: t\nconfig:\n  PORT:\n    type: integer\n    default: 8080\n  TOKEN:\n    type: string\n    secret: true\n    required: true\n",
        );
        let code = generate(&Target::TypeScript, &s, "config");
        assert!(code.contains("PORT?: string;"));
        assert!(code.contains("TOKEN: string;"));
    }

    #[test]
    fn go_maps_types_and_defaults() {
        let s = schema(
            "version: \"1\"\nservice: t\nconfig:\n  PORT:\n    type: integer\n    default: 8080\n  DEBUG:\n    type: boolean\n    default: false\n",
        );
        let code = generate(&Target::Go, &s, "config");
        assert!(code.contains("Port int64"));
        assert!(code.contains("Debug bool"));
        assert!(code.contains("strconv.ParseInt(v, 10, 64)"));
    }

    #[test]
    fn java_uses_value_annotations() {
        let s = schema(
            "version: \"1\"\nservice: t\nconfig:\n  DATABASE_URL:\n    type: string\n    required: true\n",
        );
        let code = generate(&Target::Java, &s, "com.acme");
        assert!(code.contains("package com.acme;"));
        assert!(code.contains("@Value(\"${DATABASE_URL}\")"));
    }

    #[test]
    fn python_requires_missing_keys() {
        let s = schema(
            "version: \"1\"\nservice: t\nconfig:\n  TOKEN:\n    type: string\n    secret: true\n    required: true\n",
        );
        let code = generate(&Target::Python, &s, "config");
        assert!(code.contains("TOKEN = _require(\"TOKEN\")"));
    }

    #[test]
    fn empty_schema_generates_valid_skeleton() {
        let s = EnvySchema {
            version: "1".into(),
            service: None,
            config: BTreeMap::new(),
        };
        assert!(generate(&Target::Go, &s, "config").contains("func Load()"));
    }
}
